version: "3.7"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine-0.7.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.size == small
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nihongo
    volumes:
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - sftp_data:/home
      - /opt/nginx/conf.nginx:/etc/nginx/nginx.conf
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    logging:
      options:
        max-size: "50k"
        max-file: "2"

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.size == small
    depends_on:
      - nginx-proxy
    networks:
      - nihongo
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: frog-development-it@gmail.com
    logging:
      options:
        max-size: "50k"
        max-file: "2"

  postgres:
    image: groonga/pgroonga:2.3.4-alpine-14-slim
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.size == large
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9173:5432"
    networks:
      - nihongo
    secrets:
      - postgres_password
      - postgres_user
    environment:
      TZ: Europe/Paris
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sftp:
    image: atmoz/sftp:alpine
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.size == large
    ports:
      - "22:22"
    volumes:
      - sftp_data:/home
    command: frog_admin_user:frog_admin_pwd:1001::dico,lessons

  nginx:
    image: nginx:1.23-alpine
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.size == large
    ports:
      - "88:80"
    volumes:
      - sftp_data:/home:ro
      - /opt/nginx/conf.nginx:/etc/nginx/nginx.conf:ro

secrets:
  postgres_password:
    external: true
  postgres_user:
    external: true

volumes:
  postgres_data:
  dhparam:
  vhost:
  html:
  certs:
  sftp_data:


networks:
  nihongo:
    external: true
    name: nihongo
